### ISSUE TITLE
Items array sample structure

### ISSUE THREAD

**Issue by RanaProgrammer** [heyligengregory/ionic-tree-view#1]
what is the sample array structure to provide ionic-tree-view. can you please elaborate?
on what basis this package is creating view?
can you post a sample array in JSON file here?

**Comment by heyligengregory** [comment]
Hello,

I am working on this package, I made it first for Ionic 1 but it's almost good for Ionic 2.

Below you will find an example of the data in JSON : 

`[
   {
      "id":1,
      "name":"features"
   },
   {
      "id":2,
      "name":"Add",
      "parentID":1
   },
   {
      "id":3,
      "name":"Remove",
      "parentID":1
   },
   {
      "id":9,
      "name":"Update",
      "parentID":1
   },
   {
      "id":11,
      "name":"UpdateDel",
      "parentID":9
   },
   {
      "id":27,
      "name":"Add",
      "parentID":2
   },
   {
      "id":28,
      "name":"master"
   }
]`

It will looks like : 
![image](https://user-images.githubusercontent.com/17003290/37466561-5949cd60-285e-11e8-93a2-4b33662a20ed.png)

**Comment by RanaProgrammer** [comment]
Thanks @heyligengregory 👍
