### ISSUE TITLE
Checkboxes are presisted even when the localstorage is cleared. How to reset checkboxes?

### ISSUE THREAD

**Issue by ghost** [heyligengregory/ionic-tree-view#2]
@heyligengregory if there is some code need to be changed. let me know.

**Comment by RanaProgrammer** [comment]
@heyligengregory any update?

**Comment by heyligengregory** [comment]
@RanaProgrammer Component must be updated in future, if you want, you can work on it.

**Comment by heyligengregory** [comment]
Update soon

**Comment by zsqx** [comment]
How to customize its style?

**Comment by zsqx** [comment]
> 马上更新

How to customize its style

**Comment by gowrisankarreddy** [comment]
Guys i need to display Accordion view.Its Possible this code?

**Comment by heyligengregory** [comment]
@zsqx What do you want to customize ?
