### ISSUE TITLE
Cannot find module "components/ionic-tree-view.component"

### ISSUE THREAD

**Issue by missakation** [heyligengregory/ionic-tree-view#4]
Hi,
After npm installing and importing in the module.ts, when I put the following code in the imports, I am getting Cannot find module "components/ionic-tree-view.component". Any idea why?
```
imports:
        [
            BrowserModule,
            HttpModule,
            IonicModule.forRoot(MyApp,
                {
                    mode: "md"
                }),
            CommonModule,
            IonicTreeViewModule.forRoot()

        ],
```

**Comment by em92** [comment]
Same happens.

**Comment by missakation** [comment]
I created manually. Tell me if you want a solution

**Comment by em92** [comment]
That would be cool

**Comment by missakation** [comment]
I'll email you soon

**Comment by naitikpatel1990** [comment]
Can you please mail me too on "naitikpatel1990@gmail.com" ? I got same error...

**Comment by em92** [comment]
> I'll email you soon
Suggesting to write here.

**Comment by missakation** [comment]
I am making a repository and I will share with you the project here. If you have any comments or ways to improve it you're welcome to do it.

**Comment by heyligengregory** [comment]
Hello,

I apologize for this issue, I should fix this mistake but I do not have time yet. If anyone wants to do it, he is welcome.

**Comment by missakation** [comment]
I made a repository. https://github.com/missakation/IonicTreeView

**Comment by naitikpatel1990** [comment]
Thanks @missakation  for your repository. It helps me a lot. Thank you.

**Comment by heyligengregory** [comment]
@missakation It's cool for users but it will be better if this lib was working 👍

**Comment by missakation** [comment]
I know. I was in hurry and could not find the cause of the error.

**Comment by praveen000** [comment]
@missakation  Hello I'm a beginner i want use the TreeView. How to use your repository [https://github.com/missakation/IonicTreeView](url) . in My Existing Ionic Application

**Comment by missakation** [comment]
@praveen000  Hey ask me the question there, I will answer you. Soon I will build the readme file.

**Comment by praveen000** [comment]
@missakation Thanks for Responding  i'm implementing tree view in my application I have tried you TreeView Repository 
i Got this error 
```
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'TreeData' since it isn't a known property of 'resource-tree-view'.
1. If 'resource-tree-view' is an Angular component and it has 'TreeData' input, then verify that it is part of this module.
2. If 'resource-tree-view' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

<ion-content >
  <resource-tree-view [ERROR ->][TreeData]="Family" [hasCheckbox]="true"></resource-tree-view>
</ion-content>
"): ng:///GenealogyPageModule/GenealogyPage.html@31:22
Can't bind to 'hasCheckbox' since it isn't a known property of 'resource-tree-view'.
1. If 'resource-tree-view' is an Angular component and it has 'hasCheckbox' input, then verify that it is part of this module.
2. If 'resource-tree-view' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
```
The ERROR Quite Big i have pasted half of it 
Help Me Out Here
Thank You

**Comment by missakation** [comment]
@praveen000  Hey read the "readme" file. You need to import the component in app.module.ts.
If you still have issues comment in my repository and not in this page.

**Comment by Kleisman** [comment]
Ey Thank you, 
I made some improvements for greater coupling to my code, but it was very helpful.

**Comment by heyligengregory** [comment]
Fixed

**Comment by malwareoverflow** [comment]
nothing is fixed in this library even class name is misspelled which is "IonTreeViewModule" not "IonicTreeViewModule"
