### ISSUE TITLE
Can't bind to 'items' since it isn't a known property of 'tree-view'.

### ISSUE THREAD

**Issue by malwareoverflow** [heyligengregory/ionic-tree-view#6]
Inspite of importing library inside app module still facing this error.

 Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'items' since it isn't a known property of 'tree-view'.

**Home.page.html**

<ion-content>
  <div class="ion-padding">
    The world is your oyster.
    <p>If you get lost, the <a target="_blank" rel="noopener" href="https://ionicframework.com/docs/">docs</a> will be your guide.</p>
  </div>
  <tree-view [items]="items" [persistedName]="persistedName" [treeViewName]="treeViewName"></tree-view>

</ion-content>

**Module**
`// Import library
import { IonTreeViewModule } from 'ionic-tree-view';`

**Import**

  imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule,IonTreeViewModule],

**Comment by heyligengregory** [comment]
Resolved
