### ISSUE TITLE
Styling the tree view

### ISSUE THREAD

**Issue by StefanVanStaden** [heyligengregory/ionic-tree-view#8]
In Ionic 5 the tree view styling is not quite right would it be possible to style the tree view somehow? See screenshot below the label appears tight against the checkbox and not finding anything that will allow me to style that element.
<img width="295" alt="Screenshot 2020-05-08 at 10 21 11" src="https://user-images.githubusercontent.com/20769772/81386790-e5904700-9115-11ea-8910-95fdc214a8b6.png">

**Comment by StefanVanStaden** [comment]
It would seem that Ionicons was updated and the arrow-dropright.svg changed to caret-forward.svg

**Comment by heyligengregory** [comment]
Fixed
